runtime: python39
entrypoint: gunicorn -b :$PORT thomasd9e.wsgi

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_instances: 1
  max_instances: 10

handlers:
- url: /static
  static_dir: staticfiles
- url: /.*
  script: auto
