# Generated by Django 4.2.3 on 2023-08-16 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_customuser_date_joined_customuser_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
