# Generated by Django 4.2.3 on 2023-08-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRecap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("title", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("game_id", models.CharField(max_length=50, unique=True)),
                ("processed", models.BooleanField(db_index=True, default=False)),
            ],
        ),
    ]
